# Generated by Django 4.0.5 on 2022-07-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=240)),
                ('member1', models.CharField(blank=b'I01\n', max_length=40)),
                ('member2', models.CharField(blank=b'I01\n', max_length=40)),
                ('member3', models.CharField(blank=b'I01\n', max_length=40)),
                ('member4', models.CharField(blank=b'I01\n', max_length=40)),
                ('member5', models.CharField(blank=b'I01\n', max_length=40)),
                ('image1', models.ImageField(upload_to='projects')),
                ('image2', models.ImageField(upload_to='projects')),
                ('image3', models.ImageField(upload_to='projects')),
            ],
        ),
    ]
