# Generated by Django 4.0.5 on 2022-07-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='team')),
                ('name', models.CharField(max_length=60)),
                ('role', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=60)),
                ('mail', models.CharField(max_length=60)),
                ('whatsapp', models.CharField(max_length=60)),
            ],
        ),
    ]
